export const GET_LIST_BEGIN = "GET_LIST_BEGIN";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAIL = "GET_LIST_FAIL";

export const POST_LIST_BEGIN = "POST_LIST_BEGIN";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const DELETE_LIST_BEGIN = "DELETE_LIST_BEGIN";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAIL = "DELETE_LIST_FAIL";

export const UPDATE_LIST_BEGIN = "UPDATE_LIST_BEGIN";
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";
export const UPDATE_LIST_FAIL = "UPDATE_LIST_FAIL";
